### PR TITLE
Updated dependencies, edition and fixed warnings.

### PR DESCRIPTION
**Pull request by golddranks**
Hi, I did an update to this crate. I know it's an old crate, but there are some old codebases that run on non-async hyper 0.10 with no intention to update for the time being. This version bump would be helpful for those crates.

The commits contain almost mechanistic rewrites and updates, so they should be easy to check commit-by-commit.

### CODE REVIEW

**Comment by golddranks** [comment]
Once https://github.com/mikedilger/textnonce/pull/20 lands, let us consider updating that too, for significant reduction of dependencies.

**Comment by mikedilger** [comment]
Wow I didn't realize I'd left this crate so far out of date.  Thanks for doing this. I've been away from rust projects for a little while now.

**Comment by mikedilger** [comment]
let me know if you want a version released.

**Comment by golddranks** [comment]
Version bumps for both https://github.com/mikedilger/textnonce and this crate would be nice to have!
I think that textnonce would otherwise be fine with a patch version bump, but I don't know about the minimum supported Rust version, that was likely to have risen because of the new-ish stdlib features I introduced in https://github.com/mikedilger/textnonce/pull/20 , so maybe it's safer to release 0.8.0 for textnonce.

For this crate, with the edition upgrades and all, version 0.6.0 is definitely warranted. However, updating all of the dependencies would be actually bad, because at the moment, the foremost reason to have this crate in one's build is exactly because it supports the old hyper 0.10, mime 0.2 etc. Thus, bumping just textnonce to 0.8.0 and releasing this would be the best, in my mind. Thank you!

**Comment by mikedilger** [comment]
You've got your wish.  But I made textnonce 1.0.0 because major changes completed long ago.

**Pull request merged**
